#!/bin/bash

SECONDS=0

if [ -z "$1" ]
  then
    echo "Audio/vidideo file is required. It supports any format that ffmpeg suports."
    echo "Example:"
    echo "srtof myaudio.mp3"
    exit -1
fi

################################
# [1] handling input
################################

input_file_without_ext=${1%.*}

lang=${2:-'en'}


################################
# [2] converting to compatible audio file
################################


tmpfile="$(mktemp /tmp/whispercpp.XXXXXXXXXX)" || { echo "Failed to create temp file"; exit 1; }

rm "$tmpfile"

tmpfilewav="$tmpfile.wav"

ffmpeg -i "$1" -ar 16000 -ac 1 -c:a pcm_s16le "$tmpfilewav"


################################
# [3] transcribing with Whisper
################################

whisper_cpp_dir="/Users/ecacho/apps/whisper.cpp"
model="$whisper_cpp_dir/models/ggml-medium.bin"

$whisper_cpp_dir/main -f "$tmpfilewav" -l "$lang" --output-srt --model "$model"


mv "$tmpfilewav.srt" "$input_file_without_ext.srt"

################################
# [4] removing temp file
################################

rm "$tmpfilewav"

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."

