#!/bin/python
import argparse
import dataclasses
import logging
import os
import sys
import uuid
import json
import urllib.request
import time

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

CUR_DIR = os.path.dirname(__file__)
BIN_YT_DLP = "/Users/edu/apps/yt-dlp/venv/bin/yt-dlp" #cmd tool to download youtube videos
BIN_WHISPER = os.path.join(CUR_DIR, "whispercpp") #whisper tool to transcribe audio

LANGUAGE_EN = 'en'
LANGUAGE_ES = 'es'


@dataclasses.dataclass
class RunArgs:
    youtube_url: str
    language: str # en or es
    output_filename: str

def get_video_title(youtube_url: str) -> str:
    log.info(f"Retrieving video title for: {youtube_url}")
    cmd = f"{BIN_YT_DLP} --get-title {youtube_url}"
    result = os.popen(cmd).read().strip()
    if not result:
        log.error("Failed to retrieve video title")
        sys.exit(1)
    return result


def download_video(args: RunArgs) -> str:
    log.info(f"Downloading video: {args.youtube_url}")
    output_dir = os.curdir
    video_filename = "video_" + str(uuid.uuid4()) + ".tmp"
    video_filename_abs = os.path.join(output_dir, video_filename)
    cmd = f"{BIN_YT_DLP} -o {video_filename_abs} {args.youtube_url}"
    os.system(cmd)

    # find file by prefix
    video_filename_found = None
    for file in os.listdir(output_dir):
        if file.startswith(video_filename):
            video_filename_found = file
    #

    # check if file exists
    if video_filename_found is None or not os.path.isfile(video_filename_found):
        log.error(f"Youtube download file '{video_filename}' does not exist")
        sys.exit(1)
    #
    return video_filename_found

def transcribe_video(video_filename: str, lang: str) -> str:
    log.info(f"Transcribing video: {video_filename}")

    # using whispercpp
    cmd = f"{BIN_WHISPER} '{video_filename}' '{lang}' "
    os.system(cmd)

    expected_filename = video_filename + ".txt"
    if not os.path.isfile(expected_filename):
        log.error(f"Expected file '{expected_filename}' does not exist")
        sys.exit(1)
    return expected_filename

def summarize_transcript(transcript_filename: str) -> str:
    log.info(f"Summarizing transcript: {transcript_filename}")
    prompt = "Summary the following transcript and giving me the 5 key ideas: "

    with open(transcript_filename, "r") as f:
        transcript = f.read()

    # call ollama local,

    url = 'http://localhost:11434/api/generate'
    data = {
        "model": "llama3.2",
        "prompt": f"{prompt} {transcript}",
        "stream": False
    }

    req = urllib.request.Request(url=url,
                                 method='POST',
                                 data=json.dumps(data).encode('utf-8'),
                                 headers={'Content-Type': 'application/json'})
    with urllib.request.urlopen(req) as f:
        if f.status != 200:
            log.error(f"Failed Ollama API request: {f.status} {f.reason}")
            exit(1)
        rs = f.read().decode('utf-8')
        log.info(f"Ollama API response: {rs}")

        json_rs = json.loads(rs)
    return json_rs['response']




def main(args: RunArgs):
    start_time = time.time()
    log.info(f"videosummary starts with: {args}")

    video_filename = download_video(args)
    transcribe_filename = transcribe_video(video_filename, args.language)
    summary_text = summarize_transcript(transcribe_filename)

    log.info(f"Summary:")
    log.info(summary_text)

    # write file
    with open(args.output_filename, "w") as f:
        f.write(summary_text)

    end_time = time.time()
    log.info(f"videosummary ends in {end_time - start_time} seconds")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Video summary')
    parser.add_argument('youtube_url', type=str, help='URL of the YouTube video')
    parser.add_argument('-l', '--language', choices=[LANGUAGE_EN, LANGUAGE_ES], default=LANGUAGE_EN,
                        help=f"Language to process ({LANGUAGE_EN} or {LANGUAGE_ES})")
    parser.add_argument('-o', '--output', action='store_true', default="summary.txt",
                        help="Save the summary file with a default name 'summary.txt'")

    args = parser.parse_args()

    app_args = RunArgs(
        youtube_url=args.youtube_url,
        language=args.language,
        output_filename=args.output,
    )
    main(app_args)
