#!/bin/bash


# Check if WHISPER_CPP environment variable is set
if [ -z "$WHISPER_CPP" ]; then
  echo "The WHISPER_CPP environment variable is not set."
  echo "Please set it to the path where the whisper.cpp binary is located."
  exit 1
fi

echo "Whisper path found $WHISPER_CPP"

if [ -z "$1" ]
  then
    echo "Audio file is required. It supports any audio or video file."
    echo "Example:"
    echo "whispercpp myaudio.mp3"
    echo "whispercpp myvideo.mp4"
    exit -1
fi


lang=${2:-'en'}


tmpfile="$(mktemp /tmp/whispercpp.XXXXXXXXXX)" || { echo "Failed to create temp file"; exit 1; }

rm "$tmpfile"

tmpfilewav="$tmpfile.wav"

ffmpeg -i "$1" -ar 16000 -ac 1 -c:a pcm_s16le "$tmpfilewav"

model="$WHISPER_CPP/models/ggml-medium.bin"

# model="$WHISPER_CPP/models/ggml-medium.$lang.bin"

# if not lang en
# if [ "$lang" != "en" ]; then
#   model="$WHISPER_CPP/models/ggml-medium.bin"
# fi

# $WHISPER_CPP/build/bin/whisper-cli -f "$tmpfilewav"  -l "$lang" -nt --model $model -otxt -of "$1"
$WHISPER_CPP/build/bin/whisper-cli -f "$tmpfilewav" -nt --model $model -otxt -of "$1"

rm "$tmpfilewav"